spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Capstone_Project_EMS
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    # properties:
    #    hibernate:
    #      format_sql: true