
POST http://localhost:8080/signup/ HTTP/1.1 
content-type: application/json

{ 
    "email": "daya@gmail.com",
    "password":"sujit1234", 
    "gender" :"male",
    "role":"User"
}

###
POST http://localhost:8080/signin/ HTTP/1.1 
content-type: application/json

{ 
    "email": "daya@gmail.com",
    "password":"sujit1234"
}