###  Register New User/Admin
POST http://localhost:8080/user/ HTTP/1.1 
content-type: application/json

{ 
    "email": "sujt1@gmail.com",
    "password":"assdffsf", 
    "gender" :"male",
    "role":"user"
}


###  Login Credentials (User/Admin)
POST http://localhost:8080/user/loginv2 HTTP/1.1 
content-type: application/json

{ 
    "email": "sujt@gmail.com",
    "password":"sujit1234"
}

###  Forgot Password 
POST http://localhost:8080/user/login/forgotpass HTTP/1.1 
content-type: application/json

{ 
    "email": "sujit@gmail.com"
}