
POST http://localhost:8080/user/ HTTP/1.1 
content-type: application/json

{ 
    "email": "ssscom@gmail.com",
    "password":"sujit1234", 
    "gender" :"male",
    "role":"user"
}

###
POST http://localhost:8080/user/login HTTP/1.1 
content-type: application/json

{ 
    "email": "asd",
    "password":"sujit1234"
}

###
POST http://localhost:8080/user/login/forgotpass HTTP/1.1 
content-type: application/json

{ 
    "email": "sujit@gmail.com"
}